name: reviewdog golangci-lint

on:
  push:
  pull_request:

jobs:
  rd-gcl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-golangci-lint@v2
        with:
          cache: false
          fail_on_error: true
          golangci_lint_flags: "--verbose"
          reviewdog_flags: '-fail-level=any'
          reporter: github-check
