name: reviewdog golangci-lint

on:
  push:
  pull_request:

jobs:
  rd-gcl:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6
