name: reviewdog golangci-lint

on:
  pull_request:

jobs:
  rd-gcl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-golangci-lint@v2
        with:
          filter_mode: nofilter
          golangci_lint_flags: "--verbose"
          fail_on_error: true
          # level: any
          # reviewdog_flags: '-fail-level=any'
          reporter: github-pr-check
